### ISSUE TITLE
Consider licensing under a more permissive license

### ISSUE THREAD

**Issue by hacker1024** [joaquimguimaraes/universal_disk_space#1]
Using the [LGPL license](https://choosealicense.com/licenses/lgpl-3.0/) will allow developers to use this package (leaving it open-source) without having to license their entire app under the GPL license.

Permission would be required from all contributors: @jgilfn

**Comment by vleeuwenmenno** [comment]
I am not familiar with it but I read that LGPL states the used library must be replaceable. Thus static linking isn't possible.
I am uncertain that Dart can do such a thing as it's unlike C/C++ but there might be other scenarios where this would apply in Dart.

**Comment by hacker1024** [comment]
I see. Are there any more permissive licenses you'd be open to switching to?

**Comment by gilnobrega** [comment]
@jgilfn is another account that I used in a commit by mistake. I'd be willing to change to an Apache2.0 license, are you ok with that? Is there any advantage of choosing MIT over Apache2.0?

**Comment by hacker1024** [comment]
They're pretty similar, so I don't mind. The MIT is simpler and seems more popular in the Dart community.

Thanks!

**Comment by gilnobrega** [comment]
It is very popular in the dart community. Let me think about it for a day.

**Comment by gilnobrega** [comment]
Feel free to make a PR if you wish to add your name to the LICENSE file

**Comment by hacker1024** [comment]
I don't need my name in the LICENSE. Thanks!
