### ISSUE TITLE
Not working for Android

### ISSUE THREAD

**Issue by p3et-jambit** [joaquimguimaraes/universal_disk_space#5]
On pub dev compatibility with Android is indicated. However, this minimal code:
```
final diskSpace = DiskSpace();
await diskSpace.scan();
```
leads to the following error:
```
E/flutter (18145): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot modify an unmodifiable list
E/flutter (18145): #0      UnmodifiableListMixin.sort (dart:_internal/list.dart:149:5)
E/flutter (18145): #1      DiskSpace.scan (package:universal_disk_space/src/disk_space.dart:174:11)
```
Reason:
- Disks._disks field is initially a const
- For Android (tried 2 devices 11+12) no disks are found
- diskSpace.scan() applies a sort mutation to the const

So, it should not be marked as Android compatible and the subsequent bug should be avoided by e.g.
- using an immutable solution
- making default value no const
- check for emptiness before sorting

**Comment by SatishGD9** [comment]
Any update on this ?

**Comment by gilnobrega** [comment]
This library does not support android or iOS
